/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=cloudflare/forms/wrangler.jsonc --include-runtime=false cloudflare/forms/worker-configuration.d.ts` (hash: 260b3c717f2782cabc02c687dabfba24)
interface __BaseEnv_Env {
	DB: D1Database;
	ALLOWED_HOSTNAMES: "sysvexatechnologies.com,www.sysvexatechnologies.com";
	TURNSTILE_SITE_KEY: "0x4AAAAAAEjJ3JEov2srqIrR";
	TURNSTILE_SECRET_KEY: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ALLOWED_HOSTNAMES" | "TURNSTILE_SITE_KEY" | "TURNSTILE_SECRET_KEY">> {}
}
