/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=cloudflare/forms/wrangler.jsonc --include-runtime=false cloudflare/forms/worker-configuration.d.ts` (hash: 9efdd0d851fcc1f4c502dd7b6daf9362)
interface __BaseEnv_Env {
	HYPERDRIVE: Hyperdrive;
	ALLOWED_HOSTNAMES: "sysvexatechnologies.com,www.sysvexatechnologies.com";
	TURNSTILE_SITE_KEY: "<TURNSTILE_SITE_KEY>";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ALLOWED_HOSTNAMES" | "TURNSTILE_SITE_KEY">> {}
}
