/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=cloudflare/forms/wrangler.jsonc --include-runtime=false cloudflare/forms/worker-configuration.d.ts` (hash: 5235048d11a74b73c65948acee2640bd)
interface __BaseEnv_Env {
	DB: D1Database;
	SERVICE_REQUEST_NOTIFICATIONS: SendEmail;
	ALLOWED_HOSTNAMES: "sysvexatechnologies.com,www.sysvexatechnologies.com";
	TURNSTILE_SITE_KEY: "0x4AAAAAAEjJ3JEov2srqIrR";
	NOTIFICATION_FROM: "formularios@sysvexatechnologies.com";
	NOTIFICATION_TO: "u3849730636@gmail.com";
	TURNSTILE_SECRET_KEY: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ALLOWED_HOSTNAMES" | "TURNSTILE_SITE_KEY" | "NOTIFICATION_FROM" | "NOTIFICATION_TO" | "TURNSTILE_SECRET_KEY">> {}
}
